version: '2'


services:
  platform:
    image: warchantua/innoctf
    hostname: innoctf.com
    domainname: innoctf.com
    environment:
      - VAGRANT_PATH=/innoctf
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    command: bash -c "${VAGRANT_PATH}/scripts/setup.sh;${VAGRANT_PATH}/scripts/start.sh"
    volumes:
      - ./platform:/innoctf
      - ./logs:/var/log
    depends_on:
      - mongodb
    container_name: "platform"
    links:
      - mongodb


#  mongoclient:
#    image: mongoclient/mongoclient
#    container_name: "mongoclient"
#    expose:
#      - 3000
#    networks: 
#      - outside
#    links:
#      - mongodb

#  metabase:
#    image: metabase/metabase
#    container_name: "metabase"
#    expose:
#      - 3000
#    networks: 
#      - outside
#    links:
#      - mongodb


  mongodb:
    image: mongo
    hostname: mongodb
    container_name: "mongodb"
    expose: 
      - "27017"
    volumes:
      - ./db:/data/db
      - ./platform/config/mongo/mongodb.conf:/etc/mongodb.conf


networks:
  outside:
    external: true
