// Generated by CoffeeScript 1.11.1
(function() {
  var apiOffline, loadNavbar, teacherLoggedIn, teacherLoggedInNoCompetition, userLoggedIn, userLoggedInNoCompetition, userNotLoggedIn;

  apiOffline = {
    Инфо: "/about",
    Новости: "/news"
  };

  teacherLoggedIn = {
    Задания: "/problems",
    Рейтинг: "/scoreboard",
    Класс: "/classroom",
    Инфо: {
      Инфо: "/about",
      Новости: "/news"
    },
    Аккаунт: {
      Настройка: "/account",
      Выйти: "#"
    }
  };

  teacherLoggedInNoCompetition = {
    Класс: "/classroom",
    Инфо: "/about",
    Новости: "/news",
    Аккаунт: {
      Настройка: "/account",
      Выйти: "#"
    }
  };

  userLoggedIn = {
    Задания: "/problems",
    Команда: "/team",
    Чат: "/chat",
    Рейтинг: "/scoreboard",
    Инфо: {
      Инфо: "/about",
      Новости: "/news"
    },
    Аккаунт: {
      Настройка: "/account",
      Выйти: "#"
    }
  };

  userLoggedInNoCompetition = {
    Команда: "/team",
    Чат: "/chat",
    Рейтинг: "/scoreboard",
    Инфо: {
      Инфо: "/about",
      Новости: "/news"
    },
    Аккаунт: {
      Настройка: "/account",
      Выйти: "#"
    }
  };

  userNotLoggedIn = {
    Инфо: "/about",
    Новости: "/news",
    Рейтинг: "/scoreboard",
    Войти: "/login"
  };

  loadNavbar = function(renderNavbarLinks, renderNestedNavbarLinks) {
    var navbarLayout;
    navbarLayout = {
      renderNavbarLinks: renderNavbarLinks,
      renderNestedNavbarLinks: renderNestedNavbarLinks
    };
    return apiCall("GET", "/api/user/status", {}).done(function(data) {
      navbarLayout.links = userNotLoggedIn;
      navbarLayout.topLevel = true;
      if (data["status"] === 1) {
        if (!data.data["logged_in"]) {
          $(".show-when-logged-out").css("display", "inline-block");
        }
        if (data.data["teacher"]) {
          if (data.data["competition_active"]) {
            navbarLayout.links = teacherLoggedIn;
          } else {
            navbarLayout.links = teacherLoggedInNoCompetition;
          }
        } else if (data.data["logged_in"]) {
          if (data.data["competition_active"]) {
            navbarLayout.links = userLoggedIn;
          } else {
            navbarLayout.links = userLoggedInNoCompetition;
          }
        }
      }
      $("#navbar-links").html(renderNavbarLinks(navbarLayout));
      return $("#navbar-item-logout").on("click", logout);
    }).fail(function() {
      navbarLayout.links = apiOffline;
      return $("#navbar-links").html(renderNavbarLinks(navbarLayout));
    });
  };

  $(function() {
    var renderNavbarLinks, renderNestedNavbarLinks;
    renderNavbarLinks = _.template($("#navbar-links-template").remove().text());
    renderNestedNavbarLinks = _.template($("#navbar-links-dropdown-template").remove().text());
    return loadNavbar(renderNavbarLinks, renderNestedNavbarLinks);
  });

}).call(this);
